__default__:
  time: "4:00:00"
  mem: "16G"
  threads: 4

fastqc:
  time: "2:00:00"
  mem: "8G"
  threads: 2

trim_reads:
  time: "4:00:00"
  mem: "16G"
  threads: 4

align:
  time: "12:00:00"
  mem: "96G"
  threads: 32

macs2_peaks:
  time: "8:00:00"
  mem: "32G"
  threads: 16

seacr_peaks:
  time: "4:00:00"
  mem: "32G"
  threads: 4

merge_peaks:
  time: "2:00:00"
  mem: "16G"
  threads: 4

qc_check:
  time: "1:00:00"
  mem: "4G"
  threads: 1

multiqc:
  time: "2:00:00"
  mem: "16G"
  threads: 1