# Genome configurations
genome_index: /beegfs/scratch/ric.broccoli/kubacki.michal/SRF_CUTandTAG/mm10_bowtie2_index/mm10
effective_genome_size: "1.87e9"

# Alignment parameters
bowtie2_params:
  max_fragment_length: 1000

# TSS enrichment parameters
tss_analysis:
  upstream: 2000
  downstream: 2000
  genome_gtf: "gencode.vM10.annotation.gtf"

# Visualization parameters
visualization:
  bigwig:
    bin_size: 10
    smooth_length: 50
  heatmap:
    window_size: 2000
    bin_size: 50