# Genome configurations
genome_index: /beegfs/scratch/ric.broccoli/kubacki.michal/SRF_CUTandTAG/mm10_bowtie2_index/mm10
genome_size: mm
effective_genome_size: "1.87e9"

# Alignment parameters
bowtie2_params:
  min_quality: 30
  max_fragment_length: 1000
  min_fragment_length: 100

# TSS enrichment parameters
tss_analysis:
  upstream: 2000
  downstream: 2000
  genome_gtf: "gencode.vM10.annotation.gtf"

# Visualization parameters
visualization:
  bigwig:
    bin_size: 10
    smooth_length: 50
  heatmap:
    window_size: 2000
    bin_size: 50

# Test-specific parameters
control_samples:
  EXOGENOUS: "IgM"
  ENDOGENOUS: "IgM"

# MACS2 parameters for testing
macs2_params:
  pvalue: "1e-10"
  format: "BAMPE"
  nomodel: true
  shift: -100
  extsize: 200
  keep_dup: "1"
  min_length: 150
  max_length: 1000
  broad: false
  broad_cutoff: "1e-5"
  call_summits: true

# Trim Galore parameters for testing
trim_params:
  quality: 20
  min_length: 20
  stringency: 3
  clip_r1: 0
  clip_r2: 0

# QC thresholds for testing
qc_thresholds:
  frip_score: 0.15
  tss_enrichment: 3
  peak_reproducibility: 0.7
  fragment_size:
    min: 150
    max: 1000
    nucleosome_free_max: 120
    mononucleosome_min: 150
    mononucleosome_max: 300

# Blacklist regions
blacklist:
  mm10: "mm10-blacklist.bed"