genome_index: /beegfs/scratch/ric.broccoli/kubacki.michal/SRF_CUTandTAG/mm10_bowtie2_index/mm10

genome_size: mm
EXOGENOUS_control: IgM
ENDOGENOUS_control: IgM

# Effective genome size for mouse (mm10)
effective_genome_size: "1.87e9"

# Control samples for each experiment type
control_samples:
  EXOGENOUS: "IgM"
  ENDOGENOUS: "IgM"

# MACS2 parameters for CUT&Tag
macs2_params:
  format: "BAMPE"
  qvalue: "0.05"
  keep_dup: "all"

# Alignment parameters
bowtie2_params:
  min_quality: 30
  max_fragment_length: 1000
  min_fragment_length: 100

# Trim Galore parameters
trim_params:
  quality: 20
  min_length: 20
  stringency: 3
  clip_r1: 0
  clip_r2: 0

# Add blacklist regions
blacklist:
  mm10: "mm10-blacklist.bed"

# Add TSS enrichment parameters
tss_analysis:
  upstream: 2000
  downstream: 2000
  genome_gtf: "gencode.vM10.annotation.gtf"

# Add QC thresholds
qc_thresholds:
  frip_score: 0.15
  tss_enrichment: 3
  peak_reproducibility: 0.7
  fragment_size:
    min: 150
    max: 1000
    nucleosome_free_max: 120    # For nucleosome-free regions
    mononucleosome_min: 150     # For mononucleosome-bound regions
    mononucleosome_max: 300

# # Spike-in parameters (if using spike-ins)
# spike_in:
#   genome_index: "/path/to/spike_in_genome"
#   scaling_factor: 1000000

# Visualization parameters
visualization:
  bigwig:
    bin_size: 10
    smooth_length: 50
  heatmap:
    window_size: 2000
    bin_size: 50